packages:
  - apps/*
  - packages/*
  - services/*

nodeLinker: isolated

overrides:
  'brace-expansion@>=1.0.0 <1.1.18': 1.1.18
  'browserslist@>=4.0.0 <4.28.7': 4.28.7
  'browserslist@4.28.7>baseline-browser-mapping': 2.10.44
  'fast-uri@>=3.0.0 <3.1.7': 3.1.7
  'fast-uri@>=4.0.0 <4.1.4': 4.1.4
  'find-my-way@>=9.0.0 <9.7.0': 9.7.0
  'hono@>=4.0.0 <4.13.5': 4.13.5
  'js-yaml@>=4.0.0 <4.3.1': 4.3.1
  'qs@>=6.0.0 <6.16.0': 6.16.0

allowBuilds:
  '@davisvaughan/tree-sitter-r': false
  '@homebridge/node-pty-prebuilt-multiarch': true
  esbuild: true
